import type { Venue } from "@/types/venue";
import type { Resource } from "@/types/resource";
import type { Booking } from "@/types/booking";

export const SEED_VENUE: Venue = {
  id: "venue_spr_multisport",
  name: "SPR Multisport Turf",
  location: "Ramachandra Nagar, Madurai, Tamil Nadu",
  address:
    "Ramachandra Nagar, Keelavaithiyanathapuram, Thathaneri, Madurai, Tamil Nadu",
  city: "Madurai",
  description:
    "Madurai's favourite multisport arena — turf football, badminton courts, PlayStation lounge and a full cricket ground under one roof.",
  image: "venue-hero",
  active: true,
  createdAt: new Date("2025-01-10").toISOString(),
};

export const SEED_RESOURCES: Resource[] = [
  {
    id: "res_turf_2",
    venueId: SEED_VENUE.id,
    name: "Turf 2.0",
    category: "turf",
    type: "5-a-side",
    description:
      "FIFA-approved synthetic turf with floodlights, ideal for 5-a-side football and box cricket.",
    image: "turf",
    pricePerSlot: 600,
    slotDuration: 30,
    openingTime: "14:30",
    closingTime: "23:30",
    active: true,
    amenities: ["Floodlights", "Changing room", "Drinking water", "Parking"],
  },
  {
    id: "res_turf_3",
    venueId: SEED_VENUE.id,
    name: "Turf 3.0",
    category: "turf",
    type: "7-a-side",
    description:
      "Our largest turf, built for 7-a-side matches with premium synthetic grass and stadium seating.",
    image: "turf",
    pricePerSlot: 700,
    slotDuration: 30,
    openingTime: "06:00",
    closingTime: "23:30",
    active: true,
    amenities: ["Floodlights", "Seating", "Washrooms", "Parking"],
  },
  {
    id: "res_turf_23",
    venueId: SEED_VENUE.id,
    name: "Turf 2.0 + 3.0",
    category: "turf",
    type: "Combined ground",
    description:
      "Book both turfs together for tournaments, corporate events, or large group games.",
    image: "turf",
    pricePerSlot: 1200,
    slotDuration: 30,
    openingTime: "06:00",
    closingTime: "23:30",
    active: true,
    amenities: ["Floodlights", "Seating", "Scoreboard", "Parking"],
  },
  {
    id: "res_badminton_1",
    venueId: SEED_VENUE.id,
    name: "Badminton Court 1",
    category: "badminton",
    type: "Wooden court",
    description: "Indoor wooden court with BWF-standard flooring and lighting.",
    image: "badminton",
    pricePerSlot: 300,
    slotDuration: 30,
    openingTime: "05:30",
    closingTime: "23:00",
    active: true,
    amenities: ["AC", "Wooden flooring", "Racket rental", "Washrooms"],
  },
  {
    id: "res_badminton_2",
    venueId: SEED_VENUE.id,
    name: "Badminton Court 2",
    category: "badminton",
    type: "Synthetic court",
    description: "Synthetic-mat court, great grip, popular for evening leagues.",
    image: "badminton",
    pricePerSlot: 300,
    slotDuration: 30,
    openingTime: "05:30",
    closingTime: "23:00",
    active: true,
    amenities: ["AC", "Synthetic mat", "Racket rental"],
  },
  {
    id: "res_badminton_3",
    venueId: SEED_VENUE.id,
    name: "Badminton Court 3",
    category: "badminton",
    type: "Wooden court",
    description: "Our quietest court, tucked away from the main hall — great for coaching.",
    image: "badminton",
    pricePerSlot: 300,
    slotDuration: 30,
    openingTime: "05:30",
    closingTime: "23:00",
    active: true,
    amenities: ["AC", "Wooden flooring", "Coaching available"],
  },
  {
    id: "res_ps_1",
    venueId: SEED_VENUE.id,
    name: "PS 1",
    category: "playstation",
    type: "PS5 · 55\" display",
    description: "PS5 console paired with a 55-inch 4K display and two extra controllers.",
    image: "playstation",
    pricePerSlot: 200,
    slotDuration: 30,
    openingTime: "10:00",
    closingTime: "22:30",
    active: true,
    amenities: ["4 controllers", "4K display", "Snacks counter"],
  },
  {
    id: "res_ps_2",
    venueId: SEED_VENUE.id,
    name: "PS 2",
    category: "playstation",
    type: "PS5 · 43\" display",
    description: "Cosy PS5 pod, perfect for 1v1s and quick sessions.",
    image: "playstation",
    pricePerSlot: 200,
    slotDuration: 30,
    openingTime: "10:00",
    closingTime: "22:30",
    active: true,
    amenities: ["2 controllers", "43\" display", "Snacks counter"],
  },
  {
    id: "res_cricket_ground",
    venueId: SEED_VENUE.id,
    name: "Full Ground",
    category: "cricket",
    type: "Full-size ground",
    description:
      "Full-size cricket ground with practice nets, pavilion and floodlights for night matches.",
    image: "cricket",
    pricePerSlot: 1500,
    slotDuration: 30,
    openingTime: "06:00",
    closingTime: "22:00",
    active: true,
    amenities: ["Floodlights", "Practice nets", "Pavilion", "Scoreboard"],
  },
];

// Sample bookings against Turf 2.0 today, so the slot grid visibly shows
// AVAILABLE / SELECTED / BOOKED / DISABLED on first load.
export function buildSeedBookings(todayISO: string): Booking[] {
  const now = new Date().toISOString();
  return [
    {
      id: "PZ-2026-000101",
      userId: "seed_user_1",
      venueId: SEED_VENUE.id,
      venueName: SEED_VENUE.name,
      resourceId: "res_turf_2",
      resourceName: "Turf 2.0",
      category: "turf",
      date: todayISO,
      startTime: "17:00",
      endTime: "18:00",
      slotIds: [
        `${todayISO}_res_turf_2_17:00`,
        `${todayISO}_res_turf_2_17:30`,
      ],
      duration: 60,
      subtotal: 1200,
      tax: 60,
      convenienceFee: 10,
      total: 1270,
      paymentStatus: "PAID",
      paymentMethod: "upi",
      bookingStatus: "CONFIRMED",
      customerName: "Arun Kumar",
      customerPhone: "9876543210",
      customerEmail: "arun@example.com",
      createdAt: now,
      updatedAt: now,
    },
  ];
}
